apiVersion: apps/v1
kind : Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp

spec: 
  replicas: 3

  selector:
    matchLabels:
      app: webapp

  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: mongo-express:latest
        ports:
        - containerPort: 8081 
        env:
        - name: ME_CONFIG_MONGODB_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: username
        - name: ME_CONFIG_MONGODB_AUTH_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: webapp-secret
              key: password

      

